artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_url: https://github.com/sanjeev-nits/data/row/main/Chicken-fecal-images.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion


Prepare_base_model:
  root_dir: artifacts/Prepare_base_model
  base_model_path: artifacts/Prepare_base_model/base_model.h5
  update_base_model_path: artifacts/Prepare_base_model/base_model_updation.h5
  


